version: "3.7"
services:
  adminer:
    image: adminer
    ports:
      - '8080:8080'


  mysql:
    image: mysql:latest
    command: "--innodb_use_native_aio=0"
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

      
        
  api:
    image: mupacif/graphnode:latest
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./server:/app
    ports:
      - '3000:3000'
    depends_on:
      - mysql



  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/
  #   ports:
  #     - '4000:80'

  # client:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   volumes
  #     - /app/node_modules
  #     - ./client:/app
