version: "3.7"
services:


  mysql:
    image: mysql:latest
    command: "--innodb_use_native_aio=0"
    environment:
      MYSQL_DATABASE: reactcomp
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

      
        
  api:
    image: mupacif/appolo:latest
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    # volumes:
    #   - ./server:/app
    ports:
      - '3000:3000'
    depends_on:
      - mysql

  adminer:
    depends_on:
      - mysql
    image: adminer
    ports:
      - '8080:8080'
      
      
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9090:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: test
      PMA_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test 

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'

  # client:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   volumes
  #     - /app/node_modules
  #     - ./client:/app
