FROM node:10-alpine

RUN mkdir -p /app/node_modules && chown -R node:node /app /app/node_modules
WORKDIR /app 


COPY package*.json /app/
COPY app/db/migrations/* /app/db/migrations

#To ensure that all of the application files are owned by the non-root node user,
USER node


RUN  npm install
COPY --chown=node:node . .

EXPOSE 3000
#CMD [ "node", "server.js" ]
ENTRYPOINT [ "./entrypoint.sh" ]