FROM node:10-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app 


COPY package*.json ./

#To ensure that all of the application files are owned by the non-root node user,
USER node


RUN npm install
COPY --chown=node:node . .

EXPOSE 3000
CMD [ "node", "server.js" ]