FROM node:10-alpine

RUN mkdir -p /app/node_modules && chown -R node:node /app /app/node_modules
WORKDIR /app 


COPY package*.json /app/
#for sequelize migration
COPY /app/db/config/config.json /app/db/config/
#To ensure that all of the application files are owned by the non-root node user,
USER node


RUN  npm install; 
COPY --chown=node:node . .

WORKDIR /app/db 
RUN npx sequelize db:migrate 

WORKDIR /app
EXPOSE 3000
CMD [ "npm", "start" ]