name: main

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install lftp
        run: sudo apt install lftp
      - name: Deploy app build to paceenet
        run: cd client/build && lftp -c "set ftp:list-options -a;
              open ftp:// ${{ secrets.PTF_CAKE }}:${{ secrets.PTF_SAUCE }}@${{ secrets.PTF_PITA }};
              cd /react;
              mirror --reverse --delete --use-cache --verbose -i ."
